### ISSUE TITLE
Add Outpost2App

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/Outpost2DLL#11]
It was mentioned in the forums to add Outpost2App to Outpost2DLL. Curiously, Outpost2App has no project file associated with the collection of headers.

Also, Outpost2App.h itself seems to include no meat.

```C++
#ifndef OUTPOST2APP_H
#define OUTPOST2APP_H

// Windows stuff (HWND, HINSTANCE etc)
#define WIN32_LEAN_AND_MEAN
#include <windows.h>

// Outpost 2 stuff
#include <Outpost2DLL.h>

// Include other files here.

#endif
```

Willing to help create the MSVC project file (or just include the headers in Outpost2DLL's project file?). We probably need to decide on some sort of plan on how it should be integrated.

**Comment by DanRStevens** [comment]
That's not the right file. There should be plenty of meat in that file.

Actually, it should have kind of the reverse problem. There is too much in one file. It probably needs to be broken down into sub header files.

----

Edit: Here's a link with a download:
https://forum.outpost2.net/index.php/topic,3961.msg61270.html#msg61270

We should probably just add the file whole, and then break it apart into chunks in later refactoring.

**Comment by Brett208** [comment]
Okay, the file I was looking at is from the SVN repo at \Outpost2SVN\LevelsAndMods\trunk\API\Outpost2App.

I think it was already broken apart in the SVN repo. Maybe that can be used instead of re-breaking it apart? 

Do you want the header(s) to be added to the Outpost2DLL project or a new MSVC project?

-Brett

**Comment by DanRStevens** [comment]
Ahh ok, I see it now. The log message even indicates the header includes haven't been setup right, hence why the file appears so gutted.

> Added Outpost2App headers to version control.
>     
> These headers describe the non level related exports of Outpost2.exe. These functions can be used for mods or shell extensions for Outpost2.
>     
> This set of files is a bit rough and in need of some work. Many stucts are missing member fields. Header files might not stand on their own.
> 

----

I would like these header files added to Outpost2DLL, but in their own subfolder. We may also want to move the existing header files into their own subfolder. In the SVN -> Git conversion thread on the forums, I believe the suggestion was for Outpost2App to go into `shell/`, while the current contents get moved into `game/`.

To maintain compatibility and ease of use, the main include files should still sit at the project root.
```
Outpost2DLL.h
Outpost2App.h
game/
  // ... old header files (excluding Outpost2DLL.h)
shell/
  // ... broken down new header files (exluding Outpost2App.h)
```

Open to suggestions on the names or the organization.

----

Once things are added, things should be connected up with the necessary `#include` lines.

----

We also want to convert to `#pragma once`.

**Comment by Brett208** [comment]
Is there a way to keep the version history somehow for Outpost2App intact when bringing in the files? Maybe not worth the effort (or not possible). Just bringing it up before we merge it in.

-Brett

**Comment by DanRStevens** [comment]
There is no real version control history to worry about. It's just the single initial commit.
