### ISSUE TITLE
Removed unneeded `struct` and `enum` keywords

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/Outpost2DLL#23]
In function signatures, the parameters and return values can omit the `struct`/`class`/`union`/`enum` keywords. These keywords were needed in C, where structs had their own namespace, and so the keyword was needed for lookup/disambiguation. In C++, structs are in the same namespace as other symbols in the same enclosing scope, and so the keyword does not need to be used before the typename to refer to it. As most methods are member functions anyway, we must necessarily be using a C++ compiler.

This mainly affects code in the "shell/" folder that is part of Outpost2App.h.

Edit: The reason those keywords currently exist, is because the header file declarations were auto generated by undecorating the exported symbols from Outpost2.exe. The undecoration algorithm included the keywords by default. In the "game/" folder that is part of Outpost2DLL, those extra keywords were manually removed slowly over time as the project was worked on. The Outpost2App code got much less manual attention.

**Comment by Brett208** [comment]
I'm not seeing this in the code base. Maybe pointing out where it is occurring would help me? Or maybe @DanRStevens could just tackle if it is easier than further explaining to me.

**Comment by DanRStevens** [comment]
On the return value of the first line, and the parameter of the second line.
```
shell/TApp.h:58:	struct IDirectDraw * GetDirectDraw(void) const;
shell/IDlgWnd.h:23:	static int __fastcall PretranslateModeless(struct tagMSG *);
```

Come to think of it, those might be the only two occurrences.
