### ISSUE TITLE
Add static size checks

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/Outpost2DLL#6]
Structs and classes exported by Outpost2.exe can have static size checks added to ensure link compatibility.

**Comment by DanRStevens** [comment]
Ok, I checked into this. The structs all have static size checks, so that part looks finished.

The classes should also have static size checks added. To the compiler, there is little distinction between `class` and `struct`, so what applies to one should probably be applied to the other. If `class` definitions result in the wrong binary size, that can also cause crashes and undefined behaviour.

----

I don't know that we need to add `#pragma pack` everywhere. The platform and bit size are all fixed for this project, so I wouldn't expect changes in alignment and padding, and kind of doubt a future version of the compiler will change that. I think we can do without the directive unless we run into compile errors. In particular, if there were changes to alignment and padding, the `static_assert` size checks would catch that, so we would know to add `#pragma pack`.

**Comment by Brett208** [comment]
A couple structs already had pragma pack already, so I just extended that. I don't mind removing them. Like you mentioned, it should complain if it is needed on a particular struct or class.

**Comment by DanRStevens** [comment]
Yeah, in the past, I may have used `#pragma pack` in a few places where it wasn't strictly needed. It's likely needed for the `CommandPacket` struct, as that has a number of non-naturally aligned fields. It's not likely going to change anything for structs where all fields are 32-bit. I probably used it more liberally than needed just to be consistent, or for vague unspecified reasons that I never thought clearly about.

I could go either way with continuing to use `#pragma pack`, though I think I'm leaning slightly towards only using it when it's absolutely required. Especially now that we have `static_assert` to warn us of problems.
