### ISSUE TITLE
Add support for `DescBlockEx` export

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/Outpost2DLL#7]
There are two separate data exports found in Outpost 2 levels:
`DescBlock` - (required) contains core level details
`DescBlockEx` - (optional, multiplayer only, with AI) contains number of AI players

Currently the `ExportLevelDetails` and `ExportLevelDetailsEx` macros provide support for generating the `DescBlock` export. There is no support for generating a `DescBlockEx` struct.

We should at a minimum, declare the struct needed for `DescBlockEx` in the `RequiredExports.h` header. Perhaps it should be named `AIModDescEx` for consistency with the other struct `AIModDesc`.

As for macro names, the `ExportLevelDetailsEx` macro may have a misleading name. We may want to consider renaming it. Alternatively, we might look into expanding it so it can generate the `DescBlockEx` export.

**Comment by DanRStevens** [comment]
References:
https://forum.outpost2.net/index.php/topic,2633.0.html
https://forum.outpost2.net/index.php/topic,4941.0.html
https://forum.outpost2.net/index.php/topic,4271.0.html
https://forum.outpost2.net/index.php/topic,4273.0.html

**Comment by Brett208** [comment]
Part one of this is completed with DescBlockEx struct added.

**Comment by DanRStevens** [comment]
Tagging Pull Request #8.

----

We could potentially update the `ExportLevelDetailsEx` macro as follows:
```cpp
#define ExportLevelDetailsEx(levelDesc, mapName, techTreeName, missionType, numPlayers, maxTechLevel, bUnitOnlyMission, numAiPlayers) \
	Export const char MapName[] = mapName; \
	Export const char LevelDesc[] = levelDesc; \
	Export const char TechtreeName[] = techTreeName; \
	Export const AIModDesc DescBlock = { missionType, numPlayers, maxTechLevel, bUnitOnlyMission, MapName, LevelDesc, TechtreeName, 0 }; \
	Export const AIModDescEx DescBlockEx = { numAiPlayers };
```

Note that adding the additional parameter makes the macro not backwards compatible. You can't overload a macro based on the number of parameters, nor do they accept default values. Due to the potentially confusing name though, we may need to break backwards compatibility.

What I don't like about the above, is we'd have no direct way to export full single player details without also generating a useless `DescBlockEx` export.

It might be nice to conditionally define the `DescBlockEx` export, so it's only generated if `numAiPlayers > 0`. I'm not sure how to do that though.

Or maybe there's a trick we can use with variable macro argument lists, which might even retain backwards compatibility. Reference:
[GCC: Variadic Macros](https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html)

----

Edit:
Close, but no. The following works, but needs C++2a to behave as expected:
```cpp
#define ExportLevelDetailsEx(levelDesc, mapName, techTreeName, missionType, numPlayers, maxTechLevel, bUnitOnlyMission, numAiPlayers...) \
	Export const char MapName[] = mapName; \
	Export const char LevelDesc[] = levelDesc; \
	Export const char TechtreeName[] = techTreeName; \
	Export const AIModDesc DescBlock = { missionType, numPlayers, maxTechLevel, bUnitOnlyMission, MapName, LevelDesc, TechtreeName, 0 }; \
	__VA_OPT__(Export const AIModDescEx DescBlockEx = { numAiPlayers };)
```

I'd say that's a fail. Requiring C++2a is not an acceptable option. Especially since that defeats much of the attempt at backwards compatibility. The code would fail to compile with older compilers or older standard settings. Additionally, the required standard settings are not available for Mingw. I had to use Clang to get that to work.

----

Maybe we can split the macro, and give a new name to the old one. Perhaps `ExportLevelDetailsFull` for the existing part, and `ExportLevelDetailsEx` for the one with the extra parameter. The one with the extra parameter can just call to the existing macro for brevity.

**Comment by DanRStevens** [comment]
I was looking at the potential future proposal for:
```cpp
#define ExportLevelDetailsEx(levelDesc, mapName, techTreeName, missionType, numPlayers, maxTechLevel, bUnitOnlyMission)  // Old (Full DescBlock)
#define ExportLevelDetailsEx(levelDesc, mapName, techTreeName, missionType, numPlayers, numAiPlayers)  // Future (Simplified DescBlock + DescBlockEx)
```

I had one concern. The variants were meant to make exporting level details easier (less fields to worry about in the common case). However, the existence of multiple export macros to choose from is a complication. Should we deprecate some macros and just force full detail specification for level authors? I mean that as in, not have a Simplified / Full distinction.

I think it makes some sense to maintain a `DescBlock` versus `DescBlockEx` distinction.
